# Generated by Django 5.2 on 2025-04-22 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_messages_image_alter_messages_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinfo',
            name='members',
        ),
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, upload_to='chatphotos'),
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
