# Generated by Django 5.2 on 2025-04-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_groupinfo_members_alter_messages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='groupimg',
            field=models.ImageField(blank=True, upload_to='grouphotos'),
        ),
    ]
