# Generated by Django 5.2 on 2025-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_groupinfo_groupimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bgname',
            field=models.CharField(default='bgdefault'),
        ),
    ]
