# Generated by Django 5.2 on 2025-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userinfo_bgname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='bgname',
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='bgname',
            field=models.CharField(default='bgdefault'),
        ),
    ]
